export const benefits = {
    Silver: [
      {
        id: 1,
        benefit_name: 'Blood Test',
        description: 'Check up for 1 family member',
        subDescription: 'Earn 200 more points',
        discount_percentage: 70,
        credit_points: 20,
        validity: '31-12-2024',
      },
      {
        id: 13,
        benefit_name: 'Free physiotherapy',
        description: 'Free physiotherapy for 1 family member',
        subDescription: 'Earn 300 more points',
        discount_percentage: 100,
        credit_points: 20,
        validity: '02/2025',
      },
      {
        id: 14,
        benefit_name: '5% Off on Home Care Visit',
        description: '5% Off on next Home Care Visit',
        subDescription: 'Earn 400 more points',
        discount_percentage: 5,
        credit_points: 10,
        validity: '06/2024',
      },
    ],
    Gold: [
      {
        id: 2,
        benefit_name: 'Free Checkup',
        description: 'Check up for 2 family member',
        discount_percentage: 80,
        credit_points: 20,
        validity: '31-12-2024',
        subDescription: 'Earn 100 more points',
      },
      {
        id: 22,
        benefit_name: 'Free physiotherapy',
        description: 'Free physiotherapy for 2 family member',
        discount_percentage: 100,
        credit_points: 20,
        validity: '31-12-2024',
        subDescription: 'Earn 200 more points',
      },
      {
        id: 23,
        benefit_name: '10% Off on Home Care Visit',
        description: '10% Off on next Home Care Visit',
        discount_percentage: 10,
        credit_points: 50,
        validity: '31-12-2024',
        subDescription: 'Earn 300 more points',
      },
    ],
    Platinum: [
      {
        id: 3,
        benefit_name: 'Free Checkup',
        description: 'Check up for 4 family member',
        discount_percentage: 100,
        credit_points: 60,
        validity: '31-12-2024',
        subDescription: 'Earn 400 more points',
      },
      {
        id: 32,
        benefit_name: 'Free physiotherapy',
        description: 'Free physiotherapy for 4 family member',
        discount_percentage: 100,
        credit_points: 20,
        validity: '31-12-2024',
        subDescription: 'Earn 200 more points',
      },
      {
        id: 3,
        benefit_name: '20% Off on Home Care Visit',
        description: '20% Off on next Home Care Visit',
        discount_percentage: 20,
        credit_points: 10,
        validity: '31-12-2024',
        subDescription: 'Earn 300 more points',
      },
    ],
   
  };